# Generated by Django 2.2.4 on 2019-08-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_pk', models.IntegerField()),
                ('Teacher_disp', models.TextField(blank=True)),
            ],
        ),
    ]
