# Generated by Django 2.2.4 on 2019-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_pk', models.IntegerField()),
                ('Group_size', models.IntegerField(blank=True)),
            ],
        ),
    ]
