# Generated by Django 2.2.4 on 2019-08-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_pk', models.IntegerField()),
                ('classroom_disp', models.TextField(blank=True)),
                ('classroom_type', models.CharField(max_length=255)),
                ('classroom_cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignation_pk', models.IntegerField()),
                ('asignation_start', models.CharField(max_length=255)),
                ('asignation_end', models.CharField(max_length=255)),
                ('asignation_day', models.CharField(max_length=255)),
                ('classes_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Classes')),
                ('classroom_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Classroom')),
            ],
        ),
    ]
