# Generated by Django 2.2.4 on 2019-11-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191103_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignation',
            old_name='project_fk_id',
            new_name='project_fk',
        ),
    ]
