# Generated by Django 2.2.4 on 2019-11-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191103_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignation',
            name='project_fk',
        ),
    ]
