# Generated by Django 2.2.4 on 2019-11-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_asignation_project_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignation',
            name='project_fk',
        ),
    ]
